### PR TITLE
Add support for empty frame values & animation

### PR DESCRIPTION
**Pull request by ryanrishi**
I made a few changes that adds support for empty fill values (and animation). An example use case for something like this is visually representing loading/playing audio: it first has to load the audio (which can now be shown using empty fill), then play the audio (which can be used with normal fill, as before). This PR is a response to issue #106.

### CODE REVIEW

**Comment by ryanrishi** [comment]
Hey @kottenator, all my tests seem to be passing locally using node 6.0.0, but the Travis box seems to be out-of-date (it says it needs a C+11-compatible compiler, which isn't available on that VM). Could you please take a look at it and consider upgrading the Travis VM?

**Comment by kottenator** [comment]
As I've mentioned in #106, I'm rejecting this PR. 

However, there is useful code in it (like fixing Modernizr, updating tests & TravisCI config) - I'm going to use it in further development.

If you want to, you could create another PR, without custom functionality, but with generic fixes & improvements. Most likely, it'll get merged ;)

**Comment by andreiglingeanu** [comment]
@kottenator I've fixed Modernizr, updated tests and Travis config in #117.

**Comment by kottenator** [comment]
@ryanrishi: as I thought, part of your code has been merged, thanks to @andreiglingeanu. Good job, guys! ;)

**Comment by ryanrishi** [comment]
@kottenator Neat! Glad I could help.

**Pull request closed without merging**
