### PR TITLE
Introduce retina support

### PR DESCRIPTION
**Pull request by andreiglingeanu**
This pull request will make circles look cool on devices that have `devicePixelRatio` bigger than one.

### CODE REVIEW

**Comment by kottenator** [comment]
Please, fix the indentation in your code. 
And could you, please, add at least one test for this functionality?

**Comment by andreiglingeanu** [comment]
@kottenator I'm Sorry. Haven't checked indentation before pushing.

I've also posted some tests for this. Let me know if I'm not doing something correctly.

**Comment by andreiglingeanu** [comment]
@kottenator Is there something more I can do in order to get this merged?

**Comment by kottenator** [comment]
Try to remove `setTimeout` in your tests (and make them faster). I think you don't need them to check the canvas dimensions

**Comment by andreiglingeanu** [comment]
@kottenator The problem is that modernizr no more includes it's build into bower package.


Do you want me to go about bundling modernizr into tests directory?

**Comment by kottenator** [comment]
I'd be very happy if you'd fix it ;)

**Comment by andreiglingeanu** [comment]
@kottenator Now it is strange. It's failing only on Firefox. And only inside travis build. I'm getting straight green on my local machine.

**Comment by kottenator** [comment]
Yeah, that's strange. Did you test it locally on Firefox? Could you try to reproduce the bug somehow? (and of course, to fix it, because it's in your new tests :) )

**Comment by kottenator** [comment]
Any progress on that? I'm interested in merging your PR

**Comment by andreiglingeanu** [comment]
@kottenator I'm already using my fork in production and it works reasonable fine on every browser.

As I've said, I'm getting straight green on all tests [locally](https://i.imgur.com/aYOAi4l.png) locally. I'm not sure why it fails on travis. Maybe the version of firefox that is used there doesn't allow to change `window.devicePixelRatio` manually, via assignment?

**Comment by webjunkie** [comment]
This doesn't seem to fix the problem of having the circle loaded and then zooming in. It will still look pixelated. Can this be addressed as well or should it be a different issue?

**Comment by andreiglingeanu** [comment]
@webjunkie Can you please give me reproduction and a couple of screens, so that I can see the problem? jsfiddle would also welcome. 

I'm actually interested in finally getting this pull request done in the right way, I'm having some time now to investigate the problem.

@kottenator Nothing new about the failing tests?

**Comment by webjunkie** [comment]
@andreiglingeanu You can just zoom in to any example with your browser or mobile device. It's just a small edge case issue that is because this library relies on canvas and not something with vectors, I guess.

**Comment by andreiglingeanu** [comment]
@kottenator Hi. I'm on this. Should provide a way to fix the tests today or tomorrow.

**Comment by andreiglingeanu** [comment]
Move to #117.

**Pull request closed without merging**
