### PR TITLE
Trigger new circle-inited event on widget initalization.

### PR DESCRIPTION
**Pull request by dougt**
Add a new event that is triggered when the circle progress bar is inited or re-inited.

### CODE REVIEW

**Comment by kottenator** [comment]
Your PR looks fine for me, I could merge it.
But first, could you, please, check - why Travis CI build fails?

**Comment by kottenator** [comment]
Ping?

**Comment by dougt** [comment]
Hi Rostyslav,

I don't remember seeing this failure.  It could be that the test.html include for Modernizr is incorrect now?  I think Modernizr moved their 'top-level' js include to src/Modernizr.js.

So, try changing

https://github.com/kottenator/jquery-circle-progress/blob/master/tests/index.html#L13

to 'bower_components/modernizr/src/Modernizr.js'

**Comment by dougt** [comment]
actually Rostyslav, ignore what I said.  The safest path is to revert modernizr to 2.8.3 in bower.json.  I'll send you a pr.

**Comment by kottenator** [comment]
TravisCI build is failing. Probably because it doesn't use the recent fixes.
@dougt: could you fast-forward latest changes from `master` into your branch?

**Pull request closed without merging**
