### PR TITLE
Use ready instead of load

### PR DESCRIPTION
**Pull request by dougt**
This fixes issue #112.

I think we want to use ready() here instead because the handler is going to want to interact with the DOM.

### CODE REVIEW

**Comment by andreiglingeanu** [comment]
@dougt I'm getting #112 on my local machine, while trying to get this #83 going. Are you okay if I'll incorporate your changes in my pull request? This seems like would kill two birds at once.

**Comment by andreiglingeanu** [comment]
I've incorporated all of this in #117.

**Comment by kottenator** [comment]
@dougt: could you explain - how does `.ready()` work with `HTMLImageElement`? As I understand, it's a shortcut for `DOMContentLoaded` event, which is applicable only for `document`.

**Comment by dougt** [comment]
You could also put the callback on document:

$(document).ready(function() {....

The basic problem was that you need to wait until the dom ready until testing looking for the #qunit-feature, etc...

**Comment by kottenator** [comment]
I'm closing this PR because the change is already made in #118.

**Pull request closed without merging**
